dist: trusty
sudo: required 
language: cpp

services:
  - docker

#addons:
#  coverity_scan:
#    project:
#      name: "noahdesu/zlog"
#      description: "Build submitted via Travis CI"
#    notification_email: noahwatkins@gmail.com
#    build_command_prepend: "cmake -DWITH_JNI=ON -DWITH_CEPH=ON ."
#    build_command:   "make"
#    branch_pattern: coverity_scan
#
#env:
#  global:
#   # COVERITY_SCAN_TOKEN
#   - secure: "EhSojL5dZ7LY9S59Iixzw8KUtMqVdE8dZTZqZ0gnA1VfG4XcQr8u8Vi9jJzGaGxcXIL10p3nE4whrmhlEhUpxKkrcOgKo9vKmn9xByUHd0CBhBudZAdlQsq4DMEp20qAwg+5iuCUHS6cn3UjduQqdo9YMhfqFuRiH+U3oZxS0W4="

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - os: linux
      env: DOCKER_IMAGE=centos:7
    - os: linux
      env: DOCKER_IMAGE=fedora:26
    - os: linux
      env: DOCKER_IMAGE=fedora:25
    - os: linux
      env: DOCKER_IMAGE=fedora:24
    - os: linux
      env: DOCKER_IMAGE=debian:jessie
    - os: linux
      env: DOCKER_IMAGE=ubuntu:trusty
    - os: linux
      env: DOCKER_IMAGE=ubuntu:xenial
    - os: linux
      env: DOCKER_IMAGE=ubuntu:yakkety
    - os: linux
      env: DOCKER_IMAGE=ubuntu:zesty RUN_COVERAGE=0
    - os: linux
      env: DOCKER_IMAGE=ubuntu:zesty RUN_COVERAGE=1
    - os: osx
      env: OSX_BUILD=1

# the coverity build runs in the standard travis environment (job config #1
# from the build matrix) and needs to have the proper dependencies installed.
# all other job configurations only run ci/script.sh below which will handle
# dependency installation.
before_install:
  - if [ $TRAVIS_BRANCH == coverity_scan ] && [ ${TRAVIS_JOB_NUMBER##*.} == 1 ]; then \
      ./ci/install-zlog-deps.sh && ./ci/install-zlog.sh && ./install-deps.sh; fi
  - if [ $TRAVIS_BRANCH == coverity_scan ] && [ ${TRAVIS_JOB_NUMBER##*.} != 1 ]; then exit 0; fi

# build and testing is skipped for coverity builds
script:
  - test $TRAVIS_BRANCH != coverity_scan || exit 0
  - ci/script.sh
